services:
  - type: web
    name: cbir-vision
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_flask:app
    envVars:
      - key: PORT
        value: 5000
